#Variables

MASS_BALANCE_PORT = "COM3"

BAUDRATE = 9600

SAMPLE_RATE_AD2 = 100 #freq (Hz) to sample AD2 - check max by timing measuring loop
SAMPLE_RATE_BALANCE = 11 
DISPLAY_RATE = 2 

MEASURE_AD2_TIME = 1/SAMPLE_RATE_AD2 #time in seconds
MEAURE_BALANCE_TIME = 1/SAMPLE_RATE_BALANCE
DISPLAY_LOOP_TIME = 1/DISPLAY_RATE

MIN_FREQ = 80000
MAX_FREQ = 120000

